#Server embedded configuration

#Spring configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/holoo-user-service
    username: root
    password: pskPSK258##
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      data-source-properties:
        cacheDefaultTimeZone: false
        connectionTimeZone: SERVER
        forceConnectionTimeZoneToSession: true
  jpa:
    hibernate:
      ddl-auto: update

#Custome application configuration

#Logback logging configuration
